- name: Deploy Ansible User
  hosts: Debian-grp
  tasks:
  - name: Create Devops User
      user:
      name: devops
      groups: sudo
      append: true
      create_home: true
      comment: "Ansible Management Account"
      expires: -1
      password: "{{ 'Password1' | password_hash('sha512','A512') }}"

  - name: Create Beheer User
    user:
      name: beheer
      groups: sudo
      append: true
      create_home: true
      comment: "Management Account"
      expires: -1
      password: "{{ 'Password1' | password_hash('sha512','A512') }}"

  - name: Setup Sudo Access for Devops User
    copy:
      dest: /etc/sudoers.d/devops
      content: 'devops ALL=(ALL) NOPASSWD: ALL' 
      validate: /usr/sbin/visudo -cf %s

  - name: Setup Sudo Access for Beheer User
    copy:
      dest: /etc/sudoers.d/beheer
      content: 'beheer ALL=(ALL) NOPASSWD: ALL' 
      validate: /usr/sbin/visudo -cf %s

  - name: Deploy SSH Key
    authorized_key: user=devops
                     key="{{ lookup('file', '/home/devops/.ssh/id_rsa.pub') }}"
                     state=present

  - name: Deploy SSH Key
    authorized_key: user=beheer
                     key="{{ lookup('file', '/home/beheer/.ssh/id_rsa.pub') }}"
                     state=present
